# Generated by Django 4.2.21 on 2025-06-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.IntegerField()),
                ('ingredients', models.TextField(default='')),
                ('separate_ingredients', models.TextField(blank=True, default='', null=True)),
                ('difficulty', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('pic', models.ImageField(default='no_picture.jpg', upload_to='recipes')),
            ],
        ),
    ]
