# Generated by Django 4.2.21 on 2025-06-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_description_recipe_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='recipes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='separate_ingredients',
            field=models.TextField(default=''),
        ),
    ]
