# Generated by Django 4.2.21 on 2025-06-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_pic_recipe_separate_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='separate_ingredients',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
